class Exit(Exception):

    def __init__(self):
        return
